// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJd0ZaLcN1fN3R3CmRGrlR4rpqYP1qQ2c',
    appId: '1:718055972014:android:c4439baceaac327819613f',
    messagingSenderId: '718055972014',
    projectId: 'mojateam-76f37',
    storageBucket: 'mojateam-76f37.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyAaqTKgRQlovfLeT4X1S4jHcFtACutMM',
    appId: '1:718055972014:ios:72b1804b2e05781719613f',
    messagingSenderId: '718055972014',
    projectId: 'mojateam-76f37',
    storageBucket: 'mojateam-76f37.appspot.com',
    iosClientId: '718055972014-jkscpg1uj9m56d51dk4nlk0u5a4tt93o.apps.googleusercontent.com',
    iosBundleId: 'ke.mojateam.apps.mojateam',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmlNUbe0EvLFxgCqPer5Jn5qEGe8DMSOo',
    appId: '1:718055972014:web:351d3ab70aacea1319613f',
    messagingSenderId: '718055972014',
    projectId: 'mojateam-76f37',
    authDomain: 'mojateam-76f37.firebaseapp.com',
    storageBucket: 'mojateam-76f37.appspot.com',
    measurementId: 'G-ZE02DDV4WF',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyAaqTKgRQlovfLeT4X1S4jHcFtACutMM',
    appId: '1:718055972014:ios:72b1804b2e05781719613f',
    messagingSenderId: '718055972014',
    projectId: 'mojateam-76f37',
    storageBucket: 'mojateam-76f37.appspot.com',
    iosClientId: '718055972014-jkscpg1uj9m56d51dk4nlk0u5a4tt93o.apps.googleusercontent.com',
    iosBundleId: 'ke.mojateam.apps.mojateam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmlNUbe0EvLFxgCqPer5Jn5qEGe8DMSOo',
    appId: '1:718055972014:web:4dc4f4e94313f55219613f',
    messagingSenderId: '718055972014',
    projectId: 'mojateam-76f37',
    authDomain: 'mojateam-76f37.firebaseapp.com',
    storageBucket: 'mojateam-76f37.appspot.com',
    measurementId: 'G-1GD850Y9M2',
  );

}